# MLOps Endpoint API Configuration

# MLflow Settings
MLFLOW_TRACKING_URI: "http://localhost:5000"
MLFLOW_MODEL_NAME: "my-model"
MLFLOW_MODEL_STAGE: "Production"

# Model Settings
MODEL_TYPE: "pytorch"  # Options: "pytorch", "llm"

# API Settings
API_HOST: "0.0.0.0"
API_PORT: 8080
API_WORKERS: 1

# Feature Store Settings (Optional)
FEATURE_STORE_ENABLED: false
FEATURE_STORE_URI: ""

# LLM Settings (for LLM models)
OPENAI_API_KEY: ""
OPENAI_MODEL_NAME: "gpt-3.5-turbo"
